### PR TITLE
Miscellaneous fixes and corrections

### PR DESCRIPTION
**Pull request by grahl**
Hi 

The request mainly contains fixes for incomplete Drupal 8 conversions, especially to ldap_help, which I encountered while getting to the point until logging a user in.

Sorry for not splitting the indentation corrections in ldap_help.module into a separate commit, hope that's okay.

### CODE REVIEW

**Comment by grahl** [comment]
Addendum: I didn't realize that the pull request was branch-specific not commit-specific, I didn't actually want to suggest merging the phpcbf refactoring yet but do so in a separate request. 

Please advise if you'd like separate requests or cherry-pick if you are not interested in all commits.

**Comment by queenvictoria** [comment]
Hey thanks for all these. I think some of them have been fixed. I'll try to get time to check and pick the ones that are still outstanding. I think Github may be lagging behind D.O. now and should be retired. I'd prefer patches with separate issues at D.O.

**Comment by grahl** [comment]
Please consider closing the project down on Github.

**Comment by queenvictoria** [comment]
Thanks I will once I've copied everyone's issues to the d.o issue queue. Sorry for the inconvenience.

**Pull request closed without merging**
